### ISSUE TITLE
IndexError at line model.fit(X, y, batch_size=32, epochs=3, validation_split=0.3)

### ISSUE THREAD

**Issue by KarthikElangovan** [KarthikElangovan/questions#1]
OS..windows 7
platform ...Anaconda3, jupiter notebook,..

while working CNN in tensorflow for the following program

import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D

import pickle

pickle_in = open("X.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("y.pickle","rb")
y = pickle.load(pickle_in)

X = X/255.0

model = Sequential()

model.add(Conv2D(256, (3, 3), input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors

model.add(Dense(64))

model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(X, y, batch_size=32, epochs=3, validation_split=0.3)

i am getting error as ...

IndexError                                Traceback (most recent call last)
<ipython-input-3-c1a014dc9ece> in <module>()
     38 
     39 
---> 40 model.fit(X, y, batch_size=32, epochs=3, validation_split=0.3)
\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, max_queue_size, workers, use_multiprocessing, **kwargs)
    726         max_queue_size=max_queue_size,
    727         workers=workers,
--> 728         use_multiprocessing=use_multiprocessing)
    729 
    730   def evaluate(self,

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in fit(self, model, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_freq, **kwargs)
    222           validation_data=validation_data,
    223           validation_steps=validation_steps,
--> 224           distribution_strategy=strategy)
    225 
    226       total_samples = _get_total_number_of_samples(training_data_adapter)

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py in _process_training_inputs(model, x, y, batch_size, epochs, sample_weights, class_weights, steps_per_epoch, validation_split, validation_data, validation_steps, shuffle, distribution_strategy, max_queue_size, workers, use_multiprocessing)
    495                      'at same time.')
    496 
--> 497   adapter_cls = data_adapter.select_data_adapter(x, y)
    498 
    499   # Handle validation_split, we want to split the data and get the training

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py in select_data_adapter(x, y)
    645 def select_data_adapter(x, y):
    646   """Selects a data adapter than can handle a given x and y."""
--> 647   adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
    648   if not adapter_cls:
    649     # TODO(scottzhu): This should be a less implementation-specific error.

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py in <listcomp>(.0)
    645 def select_data_adapter(x, y):
    646   """Selects a data adapter than can handle a given x and y."""
--> 647   adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
    648   if not adapter_cls:
    649     # TODO(scottzhu): This should be a less implementation-specific error.

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py in can_handle(x, y)
    454     handles_y = True
    455     if y is not None:
--> 456       handles_y = ListsOfScalarsDataAdapter._is_list_of_scalars(y)
    457     return handles_x and handles_y
    458 

~\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\data_adapter.py in _is_list_of_scalars(inp)
    462       return True
    463     if isinstance(inp, (list, tuple)):
--> 464       return ListsOfScalarsDataAdapter._is_list_of_scalars(inp[0])
    465     return False
    466 

IndexError: list index out of range

**Comment by hanane555** [comment]
I have the same problem, do you solve it ?
